[profile.default]
src = "src"
out = "out"
libs = ["lib", "../hardhat/contracts/"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/upgradeable/contracts/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@uniswap/v2-periphery/contracts/=lib/v2-periphery/contracts/",
    "@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts/",
    "@uniswap/v3-core/contracts/=lib/v3-core/contracts",
    "velodrome/contracts/=lib/contracts/contracts/",
    "@uniswap/swap-router-contracts/contracts/=lib/swap-router-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts/",
    "@starterKit/=lib/foundry-starter-kit",
    "contracts/=../hardhat/contracts/",
    "solidity-bytes-utils/=lib/solidity-bytes-utils/",
    "sushiswap-v3-periphery/contracts/=node_modules/sushiswap-v3-periphery/contracts/",
    "forge-std/=lib/forge-std/src/",
]

allow_paths = ["../hardhat/contracts/"]